version : '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password@123
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql

  app:
    build: .
    container_name: flask_app
    depends_on:
      - db
    restart: always
    environment:
      - DB_SERVER=db
      - DB_NAME=ServiceHealthDB
      - DB_USER=sa
      - DB_PASSWORD=Password@123

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
volumes:
  db_data: