version : '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password@123
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql
  
  app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always

volumes:
  db_data: